apiVersion: v1
kind: Secret
metadata:
  name: trek-secret
type: Opaque
stringData:
  ENCRYPTION_KEY: ENC[AES256_GCM,data:f4KP6emVq7XUGHbqItKDbmSB86rLGeLsJpC/hWQx627GlT2q/8FyldAcUe6Mb92DCFqX0hgEo48Zec8mfTTuQA==,iv:pVeuNAiJ+CExtsv3I63zcc/h0wibNUevjB6XE8NSPgk=,tag:d2YROu0fNM6/04kTtuc84Q==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5M29UN0pZK1l0VWwzZFBT
        L0l6WGlHYXdtdDVFWGNKMnJRa1dsTXZjaUdJCk1aQnBBcTNyMlhnT3cvWHpvVnIy
        aHFMVTJ3MERvYWtDdHJXb21GelJ3ZU0KLS0tIDZocDNLOFUwTkZXcWl0MjgvTExv
        ZE16YUkzWjdnR253MXlvbGpkL2FiQTgKmTxVmih16KvsTNPLuPlQAr7/FegMMQgV
        lU7qC3abl7CmvXPLx7WcE7E/t8uBl5It6LDbCKWxAstle55K/fMEeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-12T18:12:20Z"
  mac: ENC[AES256_GCM,data:DLxuc8nIIEQs8+h/okLYYKKZuSLU3J1mH2OoNKG/AWAF/Qkcc8jIlJCu8C809dMc1J1MEZC05JZORYR4xHVDCsQ1Tn7y/X+SBrTHQJZ8ppyysr9d44OaIrxC6Ug9qXPV8OSaiuvwQ1dNdZOqjbe2WCHU7OnYp6JjaQXk54Cv1nQ=,iv:cCUy8zC76S7aql2DiT6qBxW/ClnRgK0psrOBmMUdc8E=,tag:ljmmVujHyxYrP+4Cpz5I5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
