---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj"
stores:
  yaml:
    indent: 2
