apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:W/ebGSYc8atZEuCpGuKI7E8wkMgTL/A9QWkZJT0su3NYen1K/q6vpg==,iv:e+aSXbDDXEsmZmSOKY+nSza5y31HmrIfoZnjbFPvzsw=,tag:ClTl+ULwmIV8Tk6HZ+YAeA==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVL2NEdldLY0xadXZGZXd3
        RVRDZ1FOdTc1M0g2VytXYUVDN3N4R1J4bnhJCnkyTHIvb1lPcnFLTFlzZTJpWUgy
        L29FWUdhbkRsdGdXMHBvcEhlUnhlVWsKLS0tIExhT21TUUpPcDd1NkpwK3VxT2FJ
        Y0ExRUV0a3V3eUR3OWR2RGZFTmR6UU0Kq7cYbJyDJq36aSLH2CD8ngx0pmw0lUL3
        i5GR9XapAL++vKySW8s+aQvGFSBIxl4A+OC4zu/tKyT6sh6lSuZJXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:05:57Z"
  mac: ENC[AES256_GCM,data:E/71/hMPHb0+Geh35KoSCCGZlVsbdIWWLSpcRfsAgXv9Pa1H1/bY1niuj2c/U7ihKpEo51FLmTs+pQR78M/RWVnR2YpZQlFVktcUnK4Adkh/iLLQDKnsa8IdAxP4dBFVS5HDivR9kjhr8b3TE3q6hoZ+KhdYykC9jvboYy0IXLY=,iv:NEspox35ydPMFwinNVWqhuUR8twgA9oM1xWSKv5sPWk=,tag:oPCuv8syGW2rXM8MF4ycdQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
