apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PW5vRAoqY4zPG3OAYTonUFvc4yVmen48aO5+J3gSvLjGicWVLHyiWw==,iv:Axkdtmd3ZP8/OyaBvEkeFSQtnRD6uqKNqvZXI1JheE0=,tag:5lSRac7o2CXar2vVkJDj5w==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlc1VpczZ2dTFMUitQN2RW
        eW1naWRSSFE5c0RaeUhZTE44dDc1NU9RQVI0CjFkTFM4UXpRNFg2cW41K2dvQVIz
        b1M5TXc2UkZQQ0M0M0ltQWJVKzc2U28KLS0tIHFoN0tkTHJ6amM0UGQ5OXM3aVZm
        bGlHdUx0Y3laZTJTZU9ocWFEdGhFR1kKWUL0XgFPyC/bC5q5Cdtr6bcL1heGr15A
        GQOksd90gNgnlP5XQKfP8wGpSZGVbHpXZqSLenWPgrStNKLdBs2yGg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:18:41Z"
  mac: ENC[AES256_GCM,data:GwjzZmf5XRzsD8pPCBIeABEaSvKJuAdE6UOtHYwBAnzZ3aeG2qV0cX1Ku9eP7ZSYUN8JRTZdBlIFEQ17rk1l7arQR+08z92TxG7unH/T0StgDOaI2brIxP5rV8OSMYFCADIaSQC9da6WuEzz7xdlzkLWLhlb6xNWV+jmLdHHQoU=,iv:0DnftllYRLzgPq7WYanRqrVBUP1/o8rC56xkLbxz+bM=,tag:UbIaMqt0YhYQMIJlf4deLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
