apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:GIXO+lUbqQrEels=,iv:iH4fKh3/VAbkYBdLa8hPaI1WK6hdd3GgfjoyhixwH4I=,tag:4j2q4IA8PXT2QZkNSz2KlA==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArakFRYzZ5OU5zMlBHTlhx
        OU8rTlpITGVzM3FhN2UySlcraERjKzU5OEI4CjRLQU83UWcxU3FMdzdDWTk3OTdZ
        ZDA1L0FQWlNJMVpoTE9GeFYrR3lRZ2cKLS0tIFpDMzRQcnh0Q3d0cXRwb21kMUVF
        OXdGWFJuRHVtT2dEdkd0S1hDMW8rLzgK73W0kqa/hYMv1QG3h2r+ax7A/KD8oiWm
        a3y2CN5PAMEkyXp7Zcnokh19FJSsCJKrob2ZpKCCKHhSKIWqDcBitQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:18:41Z"
  mac: ENC[AES256_GCM,data:C8HqQHhW7IcWGRlrKz8zwcZnREXbOksBUxvVU7QuwUQfVPYAV8kXM+A+JAjuF3y8p8XOLOzcG8lI3w/Gbrrp9K/RBtykQWkvX8+7oWMB41pb8oy3m5Jfl3kB8iHYY9+HTSPiZ/bJm//x2ys6QfN7TRSid+TmykzzmLS7LyOw1p8=,iv:q59W9v5zbIJlzqKk/Xv0Dvcn4wro741Bxtaeq+6YoJE=,tag:mCBLYofw1c5wfV14OsEbAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
