apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:UWfSk/G4QTzcjfQ=,iv:YhGj+UhX0R+BDTEK95wxcXfz/9F4JpubnGiziImiZ/c=,tag:ahgTyONRHeYjk47XJtJSBQ==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIWndpakJyd3dacWZCajBT
        SnYrV09VQWR6SlVrZFgzK09oc2pOMzEvSUcwCkRXUk8vYjNUblQ2cFg4V3hpeWhy
        VWxRc0JvOTlmZS9PamxlNldxQjBwTXMKLS0tIGdtRUtJMERNUTdWVHN2TFdkblFq
        K0w5SEg0SERrcTRkd3JiWksrMGdnRHMKs94RxA0AIpe6DyLHQpPqx3jNav4OQQwL
        dCm4yOM4/bvkqhz7i2tFEXIEaczrcfRA1sZ/yKPhpXAGcjqCliZTtg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:05:57Z"
  mac: ENC[AES256_GCM,data:KTedUvGIry3F8kGmCgTC6MZ5wiy3jHMrkaQb7imEc3xtfBrkRwFnbrB99kpFvztW8uWoO8Op4aViMkoR/mssi1OSDcLxJZ6mBdW14bzeoXsDCycOIo5KdJHlWhb+AJCUAYrOe+z4tkajfTkV2HK//Je6flcY+CJ5886MuAPqZZQ=,iv:grYeL3o+rptcdFME1uNnUV8/wDD3P5s2K0tsrBKPtu0=,tag:qwb8EXZ2vY0WdZsybUVTtA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
