apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:lfvUbLdT8RjCXH5UpCDmecBZ07AA3kvSWkOQ8TbM5eQ=,iv:gork3EN4RBl4sWpwQQLwrmA0i7LRU42Y5aEhdYsJoaY=,tag:SYqwxIsJHXYNAqcBCvqgVw==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVlJhNFhkTGpubWxNSnQz
        UzcvK1l1MStXR21xTm11NjlSdWh3TXBzeUVRClVxUzlLbEJLUy9KQjZ0cnNVNFZH
        eCtSSXNFWkZ5R0d3Q2tqUnlaODNiWHcKLS0tIDRxTm9EU0tZWGFxWW41UFhrZFVz
        TlJTdmVuUmtsMXhDZUF4ZnJxT3FrdXMKb2nR5w8qC3kkGRx+/SuGB0Ko9mHdVKtW
        6EraDn6gX8+Ls/k2Nk5ILufB3S3E5MGDOk40ntvzgYpkoM7Om/HHFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:05:57Z"
  mac: ENC[AES256_GCM,data:0WfS+0oipq5pEcpvyEkfNwXqbVmqGPJWlQujRdtkNMLjU9GbIpGfe6uIzOvS5AXzKlxEJYxmHE3Z3mp6CdxdAifIwIE26MO/ZwZCcJHh9nYIQco6Nvrx8oQYnCC6KGqNOdgGnTdiu8AakOLJJZ5uvIBhW2s7P196YiWGNHdQsOQ=,iv:3Ficc7m7/yghkK7KvMiscJvz8rbSrd09ELhYM7j6xKY=,tag:zet+4HvaNIx9lrQJN2dV5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
