apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:+GGMsqEeCPpVexwYUbcF+UI9y/QYQcTBZ6yq0NEwJ4U=,iv:85ZmurMpNMpI3yREXW6ZZnXmrNB0eJ1e5+IsO8Gllas=,tag:65Lm+Nus/HSHW1TPcJRwNg==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFOUgyTVc0dVJTYlc4NG5v
        dWZjUVV4cU00MUdhN0I5YitBbmtOQ0JuYm00Cnhjb0RQbUZ1ZFMvZmZxUkcweWMy
        WUNWS01VVVJxNzdiZFl2QTFDOU9mY3MKLS0tIHRNbEVGY2NFSDErYk1Gci9SRHlh
        YnNaRk9sVlpGSENGTG10TmdkYTFTTlkKUqL08tdbuySOPuJTrzV2Y0Qvm5784Rqi
        1j8kfdFG41NiYWhPSR70qb5gRrlQxx9WYCiTnxPZL2TN35jrOJ+IOA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:18:41Z"
  mac: ENC[AES256_GCM,data:JdSCo7foPDO/jLfWXJ9OTWROn4/9um8tnrAswhVJXI52NlqDKRDfpCmP2JJUS7eLtNaeaVDwmy8f5Ri/gAVWrPlrpFGEStRS5Q1vtBrKP/TsyNG1YrmpFmW9ntEzgXop/RBxCCLGKBwkNyEPzWWKaZ7ElM5mBMTacpq7S28Ze28=,iv:w+u+IJMcqZwJC5TRkWe9hwCGFPDjR1I8rfCs6hIllf8=,tag:Mosw13p5IicCsHtJGUIYOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
