apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:FP4Q+k32v25NSh92vIhoXhO9++eh4Oys21lJtyguFxD87nv9KSo59lR88o28uqyE/rlRnBYzGeZyUSoUr+bUa6OkAhkLsD9+Gh4B5tSrxjuilPqark50Z3o6DTU256lv7I4+KBRsiTmYopSaSvPFleuRFcKWlF9mPo0IQwsmd43/d6LX/4/Tpa5ur+m3ZCECRWIGZ3m1XhfOKA5BVmL5Y4h2+JnMZbVEzkpaf8t5hSOcBk6b,iv:+u/wqyX1xPGwH2srZFjILHZc8O1EZohE+54KphVZqL8=,tag:dD1cDdP3jp0rViNobweR4Q==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVUxlZnZma1hGUXZ2a29Y
        YUxVc1F5ckp5eXZQYVNiQzU4UTVCeHh2UTJRCjlnQWRwVTd6dWRNWmJUN3RZYVEv
        VUphUFQxeGViZkp3OTlJYXNGcTU3U1UKLS0tIGdrbVVKTSt4VnhrZUNaL2dBOVAz
        ZXJOOUoyaGZYdEFTRUdxMlp4U3BIcXcK0V+hitYPlJRzJ70hOn8RgFtdUfVjF3m9
        cr/QzOnpljkidb9+fKi9TPL9dbqTECYS4mU7Re0nbYTyolumA4aeuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:18:41Z"
  mac: ENC[AES256_GCM,data:L6xYmeUSLYJLcNdKF/61xlS3LM0IdWFb4ru30/F2sny9JrmhdJizyykoVjtLEhZ+6uvr2jn+1tY0Yj5w/793x9qlrtX8Q2m65XuVPc39dB5Uz+EBlGPOVDsemoEbX7P1Kmma7raSVOcow9h24neMuBrhLZaGkyCT2lU/YLIL/l8=,iv:P3LfZkJKT/7zFRQ3uKivL3z2DXATpDkRO5X8wA1imBY=,tag:nZci+N4e87vOgPqvvB+haw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
