apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LmxGLrxFqkRkEYMCM01IStpBONg2z4GCs4NlgOnq4eSMC/AczkeYlAUnUkNS549ZPpu1BpVBY8KobIY4QBi2T1N16BoZCYXyH3SOxlxwwQMCH/9eoZe01gd0KpG8HtKoYxC125xK9Oveqev7zvCXeyJ4YcIZVfOPJjO5kaRJU0sMiw7IIwPlS79aXQiCsWa8tGd8b91XmCWDeN7Qn5bx4mldCS7N72RuPVsWm2K1PxpQVLci,iv:jReR/yZRJwKXEph/5RSMnEHCz3ii7YgpydpeWc5XXl0=,tag:ixe93PblmNrSuq7uXvM51Q==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQjV3RnVQNUhleGM2MEh1
        Y2RqaER6NHpzeVNGczJCWmI5bGlaVkVoSEQwCmNuNHVxUmk2Qkd0SVRsRXUyNUlZ
        ZWlFaEI1bmloVnZlWng4anEzbXhwY0kKLS0tIGtLRk9TQnRyTHNZbSsvZFdaREpI
        eFUrdHNCUHIvZTFYOFFmVC9DdndwZHMKhqJWtMbA0fxkI64ALevfScBhkU+n5aRp
        H4IaFG/KuUcHlsDCCsrEffajdV7C7hetnOcpN44GoPHN0wX7fwc+/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:05:57Z"
  mac: ENC[AES256_GCM,data:YmxMvBYiZ41O2jp2Ue6Hau/Kta/jmyWky7JqjssMbs3j1QbK6fLydjwDVulWDxAbYPSf59U6PAgkUU+1yPGkeu0AuzFEpeqgoo53LhSqSJsilAn5aFkz1Lu4uZ02sDmU3+zmmPKKyLJ70HVMzGRLPHx+IufL/gX8tPf71dWmzhs=,iv:U++xtT4EWa7/sDXhzR+vBtyR9/cYrkO2sfCD1H88mkw=,tag:rAgu6RAt90DdgT9GdBs19w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
