apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:0QdHROstnDe94rndos2U1iVb75snARWXshIvnBKKtQGDe6IRkJAu0g==,iv:C6cGVemE3hoMnPPZ+jbRDKriF6znaN8Fsojwk3VtAag=,tag:OrFR3ujERhUxiV/RpIzYZg==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZCtRMTNWa3JvQzF1N2Jt
        TjZtS3FlRVNpS0l2MldseFJLdlNFVWE5UEVRCmV2cXRNS2lUeXRvNW4xWFowdHRX
        cEVQMFlpaHFrY2tCRk5maC9jUnFkemMKLS0tIHZ1K25qSWdUUjg2UytmSTM4b0ti
        bVd4bkJzMzU0WGJ0YnNJUW9mWlRWVUEKjQyZlkWiRwgZ+uoBOF/3+Xfj4txe3fUT
        ffOfBkIaadtq62TeddGtlZJPbznka3MI/Y2um8xBPQtGdZjukpSQkQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:18:41Z"
  mac: ENC[AES256_GCM,data:F0pO0Uxnt+4Pu+GUG3WLGsP5YWS044PHGvbEbc21J1FX2TlvMPJJ2LI0WMIdX9EfE17Cu32OsAisuY9OHhRfY05JLrJF7MKd5whHOmgyCQfxggcL2kjcIj2kvIONYeg6HNcYR0Da9D/RXCNFZrlZZa2uSI3QBGp5kv7jwwlWDA4=,iv:bhXPfXCMeW9AcZ2BzBh28nP5fmABnpDmep51HxqRARY=,tag:v8yfvgkx9JxBXwKFeDZyWw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
