apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:bIiSYqS643+oAMNGbaJ84DnGduYJcpGsTkUEN/bwfE8XfXkGy5rO1g==,iv:7s0WCKEIW6yMMCb3mXIocbY4RovpCZzKkLzaIRzGesw=,tag:sLqLr08b/sq1aNUcbxhkGg==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SEpqYTZRQ3hzbVlTcWp1
        SzNTN0VFY1NRSk1qSStvdTFwb0MxQU4wQ2t3CnJzYXNOSTBxN2M4aDdlWnlCaDhi
        Qyt2WGVwN0YvMmxCSWh2NHNGd01xYUkKLS0tIDBvTDBORHkrZk5TMGVCejRXT2ZR
        SWNrQ1JSRzZUWDBUOGF3QU0yb0U1WmsKvPtrzDWLwIkCjG/vEfpxoldu/oG1BXtU
        sn7G+k325vinrssc36B953uyLGRRA5kZI+PdfO+XgiXCwyBOXPZKzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-13T21:05:57Z"
  mac: ENC[AES256_GCM,data:wnvRwPRwAjN1XtzvvOQVj4emJS/p4yGiCHSxO428z6cKK7DYKWqipaT7nNUj4t+xKW3TEat0skZf7KnIa0p35X5T+x+1BRORqON8b/Ft0vflmx5YNRfOwG9XuIbnN6VvZa3RE9F+4oGfJtw3AD926BpPs1XbaenlD/TZzjtu2s0=,iv:yvX7zCY4rWQ9X6f9E5hT5WXMUCaArJXR9Uc+kmw2SWY=,tag:woZIqOseJAfwk8ZjHOiqng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
