apiVersion: v1
kind: Secret
metadata:
  name: tns-csi-secret
stringData:
  apiKey: ENC[AES256_GCM,data:nERG01kaMw9kGSMBYVa59JwCbM2RuOLAtaJ88Bm/+U+8RcAytSuBo+/msfCDKtmlGysf/e/WqD/7dAX2vUEeyPYk,iv:4wLq0sd7oY8qC+1Ki7uXqzt+d0Sgpj3rUEr2WAwXG4o=,tag:p5YFhE2z0dq3/mzACS6Bgg==,type:str]
  truenasUrl: ENC[AES256_GCM,data:skLR0YSkCRZgSPtt3sTv3TPvSeSFohLyGtLRxqSJH3o+s7wu,iv:jN8WNe5d6tHpqNp7ppaMpWMiX0b8QhEG5ZmMGf55YJc=,tag:Jt1hWKl8STLAO6S+/poB1A==,type:str]
  truenasServer: ENC[AES256_GCM,data:GP+d2jxYRN+RXol5zyg=,iv:s3WYqEtvcLLPY0ozXGcSqS7INLkhiMQI1GF38DTdIuQ=,tag:U1Bawx9HGhKbbgE7s4e6oQ==,type:str]
sops:
  age:
    - recipient: age1vyl3eet632wd4xh7zfgp44z4qkafpj0tlpn246jpqezrh5zg496s68jrjj
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3V3NCa08vaXhOYnZVc2Fh
        ZmJISUgxdXUzSS9sMXBIcjdBTk1Qd1crM0J3Ck9XSjdYdmZlUGlqMXMxdWkxSmIv
        N3JRM2EvUFNmZ1Jneml4VUlRL2ZMWjQKLS0tIDJDM3hiQ2VVOUEzdlZodHQzVThl
        UFRsNW1TTlJieUE3TVFJTHpjNVJOcUkKVad3kX2jRfhzq3ZnhkTDWI97uOrjrG1T
        Qi/FV6ZlZNygelNFp897jFqM59GT7cJddRa1+r6Fb32OA7dICkyZSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-20T21:39:39Z"
  mac: ENC[AES256_GCM,data:5vCSwbl6W+MSNqiorKNdP29XVyGvP+WBp+kzB929BIQiUVMT7HwwPYEx6EqCMw3PQwoa4b8Ms0hTpQYnp6yxXzWSWUqjqtCqPbnaNOvhDEy+elRBu/LHmTROCuCT3wUORTY6Mg6PMt3fTuDP2jsSFgOGnmiFj40zNdqkchQAYMc=,iv:/pU0xidQFkRgYQp+JNPQMJECQQPU0qAsiIOZhFUuC14=,tag:WiJYNtHItpS+ye/yCMaR8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
